
import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from './hooks/useAuth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AuthProvider>
        <div className='relative h-screen bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]'>
            {children}
          </div>
       
        </AuthProvider>
   
        


      </body>
    </html>
  )
}
